name: "PBRP Build Action"
author: 'mlm-games'
description: "A GitHub action to build PitchBlack Recovery Project (PBRP) for a specified device."

inputs:
  MANIFEST_BRANCH:
    description: 'PBRP Manifest Branch'
    default: 'android-12.1'
    required: false
    type: choice
    options:
      - android-12.1
      - android-11.0
      - android-10.0
      - android-9.0
      - android-8.1
      - android-7.1
      - android-6.0
  DEVICE_TREE:
    description: 'Custom Recovery Tree URL (your device tree repository)'
    default: "https://github.com/${{ github.repository }}"
    required: false
    type: string
  DEVICE_TREE_BRANCH:
    description: 'Custom Recovery Tree Branch'
    default: 'main'
    required: false
    type: string
  DEVICE_NAME:
    description: 'Specify your Device Codename (leave blank to auto-detect)'
    default: ''
    required: false
    type: string
  DEVICE_PATH:
    description: 'Specify your Device Path (leave blank to auto-detect)'
    default: ''
    required: false
    type: string
  BUILD_TARGET:
    description: 'Specify your Build Target (use "pbrp" for Android 11 or above)'
    default: 'recovery'
    required: false
    type: choice
    options:
      - pbrp
      - boot
      - recovery
      - vendorboot
  LDCHECK:
    description: 'Use LDCHECK (true/false)'
    default: 'false'
    required: false
    type: boolean
  LDCHECKPATH:
    description: 'Path of blobs to check (for LDCHECK)'
    default: 'system/bin/qseecomd'
    required: false
    type: string

runs:
  using: 'composite'
  steps:
    - name: Set up environment variables
      shell: bash
      run: |
        echo "MANIFEST_BRANCH=${{ inputs.MANIFEST_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_TREE=${{ inputs.DEVICE_TREE }}" >> $GITHUB_ENV
        echo "DEVICE_TREE_BRANCH=${{ inputs.DEVICE_TREE_BRANCH }}" >> $GITHUB_ENV
        echo "DEVICE_NAME=${{ inputs.DEVICE_NAME }}" >> $GITHUB_ENV
        echo "DEVICE_PATH=${{ inputs.DEVICE_PATH }}" >> $GITHUB_ENV
        echo "BUILD_TARGET=${{ inputs.BUILD_TARGET }}" >> $GITHUB_ENV
        echo "LDCHECK=${{ inputs.LDCHECK }}" >> $GITHUB_ENV
        echo "LDCHECKPATH=${{ inputs.LDCHECKPATH }}" >> $GITHUB_ENV

    - name: 'Build PBRP'
      shell: bash
      run: |
        bash $GITHUB_ACTION_PATH/entrypoint.sh

branding:
  icon: "terminal"
  color: "orange"
