name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

    - name: Update packages
      run: |
        sudo apt update && sudo apt upgrade -y
   - name: Install dependencies
        run: |
          sudo apt install -y libncurses6 python3

    - name: Clean-up
      uses: rokibhasansagar/slimhub_actions@main

    - name: Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 16

    - name: Install dependencies
      run: |
        sudo apt install -y libncurses6 libncursesw6 libncurses-dev python3

    - name: Build PitchBlack Recovery
      uses: mlm-games/pitchblack-pbrp-builder-action@main
      id: build
      with:
        MANIFEST_BRANCH: 'android-12.1'
        DEVICE_TREE: 'https://github.com/neepnttt8/twrp_device_samsung_m14x'
        DEVICE_TREE_BRANCH: 'pbrp'
        BUILD_TARGET: 'pbrp'
